blacklist:
    hg19: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/blacklist/hg19-blacklist.v2.bed.gz
    hg38: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/blacklist/hg38-blacklist.v2.bed.gz
    mm10: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/blacklist/mm10-blacklist.v2.bed.gz

bwa_index:
    hg19 : /nfs/turbo/epicore-active/genomes/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa
    hg38 : /nfs/turbo/epicore-active/genomes/Homo_sapiens/UCSC/hg38/Sequence/BWAIndex/genome.fa
    mm10 : /nfs/turbo/epicore-active/genomes/Mus_musculus/UCSC/mm10/Sequence/BWAIndex/genome.fa

tss:
    hg19: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/tss/hg19.tss.refseq.bed.gz
    hg38: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/tss/hg38.tss.refseq.bed.gz
    mm10: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/ChIPseq_ATACseq_pipelines/data/references/tss/mm10.tss.refseq.bed.gz

deeptools_bamcoverage_params: "--binSize 25 --normalizeUsing CPM --extendReads"
deeptools_bamcoverage_use_blacklist: False
samtools_prune_flags: "-f 0x1 -f 0x2 -F 0x4 -F 0x8 -F 0x100 -F 0x400 -F 0x800"
macs2_params:
    default_params: "-f BAMPE --keep-dup all"
