__default__:
    account: cgates1
    memory: '6144'
    name: '{rule}_{wildcards.sample}'
    nodes: '1'
    ntask: '1'
    partition: standard
    time: 00:30:00
ataqv_make_viewer:
    name: '{rule}'
bwa_aln:
    memory: '16384'
    name: '{rule}_{wildcards.sample}_R{wildcards.read}'
    ntask: '8'
    time: 01:00:00
bwa_mem:
    memory: '16384'
    name: '{rule}_{wildcards.sample}'
    ntask: '8'
    time: 01:00:00
bwa_sampe:
    name: '{rule}_{wildcards.sample}'
    time: 04:00:00
bwa_samse:
    name: '{rule}_{wildcards.sample}'
    time: 04:00:00
deeptools_bamcoverage_bw:
    time: 02:00:00
fastqc:
    name: '{rule}'
    ntask: '8'
    time: 01:00:00
findMotifsGenome:
    time: 04:00:00
mark_duplicates:
    memory: '16384'
    ntask: '2'
    time: 02:00:00
picard_sort:
    name: '{rule}_{wildcards.sample}'
